### ISSUE TITLE
Unable to run docker-compose up

### ISSUE THREAD

**Issue by arunsathiya** [timvisee/send-docker-compose#1]
I have tried setting up this template on both Google Cloud Platform (with ports 80 and 443 open) and DigitalOcean 5 USD basic droplet, but I run into this error after entering `docker-compose up`:

```
root@send:~/send-docker-compose# docker-compose up
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 403, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1252, in request
  File "http/client.py", line 1298, in _send_request
  File "http/client.py", line 1247, in endheaders
  File "http/client.py", line 1026, in _send_output
  File "http/client.py", line 966, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 205, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 228, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 132, in get_project
  File "compose/cli/docker_client.py", line 43, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 188, in __init__
  File "docker/api/client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[1748] Failed to execute script docker-compose
```

Should I be installing certain dependencies to move forward? I followed the Linux guide on [this page](https://docs.docker.com/compose/install/) to install Docker Compose. In fact, `docker-compose version` shows the number as expected. 

```
root@send:~# sudo curl -L "https://github.com/docker/compose/releases/download/1.27.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   651  100   651    0     0   6642      0 --:--:-- --:--:-- --:--:--  6642
100 11.6M  100 11.6M    0     0   764k      0  0:00:15  0:00:15 --:--:-- 2142k
root@send:~# sudo chmod +x /usr/local/bin/docker-compose
root@send:~# docker-compose --version
docker-compose version 1.27.3, build 4092ae5d
```

Thanks for taking a look!

**Comment by timvisee** [comment]
Interesting. Haven't seen this before. It might be a permission error, which compose doesn't handle to well.

Have you tried using `sudo docker-compose up`?

You can add your current user to the `docker` group (and do a few other things) to make Docker usable without root permissions. It's explained in [this](https://docs.docker.com/engine/install/linux-postinstall/) guide (and is commonly missed). Be sure to reboot your system after making these changes.

**Comment by arunsathiya** [comment]
I tried both options, but I continued to see issues on Google Cloud Platform. I ensured that I restarted the compute engine as well, but no luck. It's probably a mistake on my part. I will look more into that later.

For now, I started using [DigitalOcean's Docker image](https://marketplace.digitalocean.com/apps/docker) and the setup looks good. (I am having some SSL certificate generation issues, but I have some ideas to try tomorrow from [this search](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues?q=is%3Aissue+%22Custom+Diffie-Hellman+group+found%22+is%3Aclosed))

Thanks again!

**Comment by timvisee** [comment]
Good luck!

**Comment by ivsanro1** [comment]
This is also happening to me with a container I am running in a Google Cloud instance.

**My docker image is completely unrelated to this repository/project**. I am just posting this here because it seems to be an error from Google Cloud's side, as I have read the author was also running the container in a Google Cloud instance, and it seems to work correctly in other cloud providers (e.g. Digital Ocean)

My backtrace:

```
Traceback (most recent call last):
  File "requests/adapters.py", line 449, in send
  File "urllib3/connectionpool.py", line 727, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 677, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1277, in request
  File "http/client.py", line 1323, in _send_request
  File "http/client.py", line 1272, in endheaders
  File "http/client.py", line 1032, in _send_output
  File "http/client.py", line 972, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "compose/cli/log_printer.py", line 168, in tail_container_logs
  File "compose/cli/log_printer.py", line 185, in wait_on_exit
  File "compose/container.py", line 268, in wait
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/container.py", line 1305, in wait
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 233, in _post
  File "requests/sessions.py", line 578, in post
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
```
