### ISSUE TITLE
Uploading of files does not work

### ISSUE THREAD

**Issue by Avskum** [timvisee/send-docker-compose#5]
`Fields":{"error":"Error: ENOENT: no such file or directory, unlink '/uploads/1-dc687242de8542d9'","stack":"\n    at Object.unlinkSync (node:fs:1718:3)\n    at WriteStream.<anonymous> (/app/server/storage/fs.js:33:12)\n    at WriteStream.emit (node:events:402:35)\n    at WriteStream.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}}`

**Comment by sakoula** [comment]
I have the exact same issue, with local storage. I tried it without nginx (with port forwarding over ssh) and get the same issue. So it is not the reverse proxy. From the logs:

```
$ docker-compose up
[+] Running 2/2
 ⠿ Container send-redis-1  Created                                                                                           0.2s
 ⠿ Container send          Created                                                                                           0.2s
Attaching to send, send-redis-1
send-redis-1  | 1:C 18 Feb 2022 07:10:40.446 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
send-redis-1  | 1:C 18 Feb 2022 07:10:40.446 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
send-redis-1  | 1:C 18 Feb 2022 07:10:40.446 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
send-redis-1  | 1:M 18 Feb 2022 07:10:40.447 * monotonic clock: POSIX clock_gettime
send-redis-1  | 1:M 18 Feb 2022 07:10:40.447 * Running mode=standalone, port=6379.
send-redis-1  | 1:M 18 Feb 2022 07:10:40.447 # Server initialized
send-redis-1  | 1:M 18 Feb 2022 07:10:40.447 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
send-redis-1  | 1:M 18 Feb 2022 07:10:40.447 * Loading RDB produced by version 6.2.6
send-redis-1  | 1:M 18 Feb 2022 07:10:40.447 * RDB age 16 seconds
send-redis-1  | 1:M 18 Feb 2022 07:10:40.447 * RDB memory usage when created 0.79 Mb
send-redis-1  | 1:M 18 Feb 2022 07:10:40.447 # Done loading RDB, keys loaded: 0, keys expired: 0.
send-redis-1  | 1:M 18 Feb 2022 07:10:40.448 * DB loaded from disk: 0.000 seconds
send-redis-1  | 1:M 18 Feb 2022 07:10:40.448 * Ready to accept connections
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | [ 'https://send.xxx.xx', 'wss://send.xxx.xx' ]
send          | {"Timestamp":1645168294025000000,"Logger":"FirefoxSend","Type":"uncaughtException","Severity":0,"Pid":1,"EnvVersion":"2.0","Fields":{"error":"Error: ENOENT: no such file or directory, unlink '/uploads/1-2cd05a99a599b4b4'","stack":"\n    at Object.unlinkSync (node:fs:1718:3)\n    at WriteStream.<anonymous> (/app/server/storage/fs.js:33:12)\n    at WriteStream.emit (node:events:402:35)\n    at WriteStream.emit (node:domain:475:12)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process
```


btw is it normal to get this error on the redis instance?

**Comment by sakoula** [comment]
Hi again this is the solution: https://github.com/timvisee/send-docker-compose/issues/3

Thanks Tim for the great work!

**Comment by timvisee** [comment]
@sakoula Happy to see you found a fix.

@Avskum Are you still having this issue?

**Comment by Avskum** [comment]
> @sakoula Happy to see you found a fix.
> 
> @Avskum Are you still having this issue?

No thank you, this fixed the issue :-)
